#pragma once
// This file was autogenerated. Do not edit. //
#include "input.h"

void bind_input(nb::module_ &m) 
{
  // Classes

  nb::class_<Test>(m, "Test").def("overload", &Test::overload, "&a"_a,
                                  "Hi\n\nArgs:\n    a: Hello");
  nb::class_<Test2>(m, "Test2").def("trivial", &Test2::trivial, "Hive");

  // Functions
  m.def("free", nb::overload_cast<int, double>(&free), "a"_a, "b"_a,
        "A free function\n\nArgs:\n    a: Hello\n    b: Bye\n\nReturns: Fye");
  m.def("free", nb::overload_cast<char>(&free), "c"_a,
        "Hello\n\nArgs:\n    Bye: Heat death of the universe");
  m.def("free2", &free2, "Bye\n\nReturns: int");

  // Enums
};
